import { zodResolver } from '@hookform/resolvers/zod';
import { Button, Col, DatePicker, Form, Input, Row, Select, Space, Typography } from 'antd';
import dayjs from 'dayjs';
import type { FC } from 'react';
import { Controller, useForm } from 'react-hook-form';
import type { EmployeeFormInput } from '../../schemas';
import { PersonalInfoFormSchema } from '../../schemas';

const { Title, Text } = Typography;

type PersonalInfoFormValues = (typeof PersonalInfoFormSchema)['_input'];

interface PersonalInfoStepProps {
  initialData?: Partial<EmployeeFormInput>;
  onNext: (data: Partial<EmployeeFormInput>) => void;
  onCancel: () => void;
}

/**
 * Step 1: Personal Information Form
 * Collects basic personal details, national ID, and emergency contact
 */
export const PersonalInfoStep: FC<PersonalInfoStepProps> = ({ initialData, onNext, onCancel }) => {
  const {
    control,
    handleSubmit,
    formState: { errors },
  } = useForm<PersonalInfoFormValues>({
    resolver: zodResolver(PersonalInfoFormSchema),
    defaultValues: {
      // employeeCode will be auto-generated by backend
      firstName: initialData?.firstName || '',
      lastName: initialData?.lastName || '',
      thaiFirstName: initialData?.thaiFirstName || '',
      thaiLastName: initialData?.thaiLastName || '',
      nickname: initialData?.nickname || '',
      email: initialData?.email || '',
      personalEmail: initialData?.personalEmail || '',
      phoneNumber: initialData?.phoneNumber || '',
      dateOfBirth: initialData?.dateOfBirth || '',
      gender: initialData?.gender || 'male',
      maritalStatus: initialData?.maritalStatus || 'single',
      nationality: initialData?.nationality || 'ไทย',
      religion: initialData?.religion || '',
      nationalId: initialData?.nationalId || '',
      emergencyContactName: initialData?.emergencyContactName || '',
      emergencyContactRelationship: initialData?.emergencyContactRelationship || '',
      emergencyContactPhone: initialData?.emergencyContactPhone || '',
      photoURL: initialData?.photoURL || '',
    },
  });

  const onSubmit = (data: PersonalInfoFormValues) => {
    const parsed = PersonalInfoFormSchema.parse(data);
    onNext(parsed);
  };

  return (
    <Form layout="vertical" onFinish={handleSubmit(onSubmit)}>
      <Title level={4}>ข้อมูลส่วนบุคคล</Title>
      <Text type="secondary">กรุณากรอกข้อมูลพนักงานให้ครบถ้วน (รหัสพนักงานจะถูกสร้างอัตโนมัติ)</Text>

      {/* Name Fields */}
      <Title level={5} style={{ marginTop: '24px' }}>
        ชื่อ-นามสกุล
      </Title>
      <Row gutter={16}>
        <Col xs={24} md={8}>
          <Form.Item
            label="ชื่อ (English)"
            required
            validateStatus={errors.firstName ? 'error' : ''}
            help={errors.firstName?.message}
          >
            <Controller
              name="firstName"
              control={control}
              render={({ field }) => <Input {...field} placeholder="John" />}
            />
          </Form.Item>
        </Col>
        <Col xs={24} md={8}>
          <Form.Item
            label="นามสกุล (English)"
            required
            validateStatus={errors.lastName ? 'error' : ''}
            help={errors.lastName?.message}
          >
            <Controller
              name="lastName"
              control={control}
              render={({ field }) => <Input {...field} placeholder="Doe" />}
            />
          </Form.Item>
        </Col>
        <Col xs={24} md={8}>
          <Form.Item
            label="ชื่อเล่น"
            validateStatus={errors.nickname ? 'error' : ''}
            help={errors.nickname?.message}
          >
            <Controller
              name="nickname"
              control={control}
              render={({ field }) => <Input {...field} placeholder="John" />}
            />
          </Form.Item>
        </Col>
      </Row>

      <Row gutter={16}>
        <Col xs={24} md={12}>
          <Form.Item
            label="ชื่อ (ไทย)"
            required
            validateStatus={errors.thaiFirstName ? 'error' : ''}
            help={errors.thaiFirstName?.message}
          >
            <Controller
              name="thaiFirstName"
              control={control}
              render={({ field }) => <Input {...field} placeholder="จอห์น" />}
            />
          </Form.Item>
        </Col>
        <Col xs={24} md={12}>
          <Form.Item
            label="นามสกุล (ไทย)"
            required
            validateStatus={errors.thaiLastName ? 'error' : ''}
            help={errors.thaiLastName?.message}
          >
            <Controller
              name="thaiLastName"
              control={control}
              render={({ field }) => <Input {...field} placeholder="โด" />}
            />
          </Form.Item>
        </Col>
      </Row>

      {/* Contact Information */}
      <Title level={5} style={{ marginTop: '16px' }}>
        ข้อมูลติดต่อ
      </Title>
      <Row gutter={16}>
        <Col xs={24} md={8}>
          <Form.Item
            label="อีเมลบริษัท"
            required
            validateStatus={errors.email ? 'error' : ''}
            help={errors.email?.message}
          >
            <Controller
              name="email"
              control={control}
              render={({ field }) => (
                <Input {...field} type="email" placeholder="john@company.com" />
              )}
            />
          </Form.Item>
        </Col>
        <Col xs={24} md={8}>
          <Form.Item
            label="อีเมลส่วนตัว"
            validateStatus={errors.personalEmail ? 'error' : ''}
            help={errors.personalEmail?.message}
          >
            <Controller
              name="personalEmail"
              control={control}
              render={({ field }) => <Input {...field} type="email" placeholder="john@gmail.com" />}
            />
          </Form.Item>
        </Col>
        <Col xs={24} md={8}>
          <Form.Item
            label="เบอร์โทรศัพท์"
            required
            validateStatus={errors.phoneNumber ? 'error' : ''}
            help={errors.phoneNumber?.message}
          >
            <Controller
              name="phoneNumber"
              control={control}
              render={({ field }) => <Input {...field} placeholder="0812345678" maxLength={10} />}
            />
          </Form.Item>
        </Col>
      </Row>

      {/* Personal Details */}
      <Title level={5} style={{ marginTop: '16px' }}>
        ข้อมูลส่วนตัว
      </Title>
      <Row gutter={16}>
        <Col xs={24} md={6}>
          <Form.Item
            label="วันเกิด"
            required
            validateStatus={errors.dateOfBirth ? 'error' : ''}
            help={errors.dateOfBirth?.message}
          >
            <Controller
              name="dateOfBirth"
              control={control}
              render={({ field }) => (
                <DatePicker
                  {...field}
                  value={field.value ? dayjs(field.value) : null}
                  onChange={(date) => field.onChange(date ? date.format('YYYY-MM-DD') : '')}
                  style={{ width: '100%' }}
                  placeholder="เลือกวันเกิด"
                  format="DD/MM/YYYY"
                />
              )}
            />
          </Form.Item>
        </Col>
        <Col xs={24} md={6}>
          <Form.Item
            label="เพศ"
            required
            validateStatus={errors.gender ? 'error' : ''}
            help={errors.gender?.message}
          >
            <Controller
              name="gender"
              control={control}
              render={({ field }) => (
                <Select {...field} placeholder="เลือกเพศ">
                  <Select.Option value="male">ชาย</Select.Option>
                  <Select.Option value="female">หญิง</Select.Option>
                  <Select.Option value="other">อื่นๆ</Select.Option>
                </Select>
              )}
            />
          </Form.Item>
        </Col>
        <Col xs={24} md={6}>
          <Form.Item
            label="สถานภาพสมรส"
            required
            validateStatus={errors.maritalStatus ? 'error' : ''}
            help={errors.maritalStatus?.message}
          >
            <Controller
              name="maritalStatus"
              control={control}
              render={({ field }) => (
                <Select {...field} placeholder="เลือกสถานภาพ">
                  <Select.Option value="single">โสด</Select.Option>
                  <Select.Option value="married">สมรส</Select.Option>
                  <Select.Option value="divorced">หย่า</Select.Option>
                  <Select.Option value="widowed">หม้าย</Select.Option>
                </Select>
              )}
            />
          </Form.Item>
        </Col>
        <Col xs={24} md={6}>
          <Form.Item
            label="สัญชาติ"
            required
            validateStatus={errors.nationality ? 'error' : ''}
            help={errors.nationality?.message}
          >
            <Controller
              name="nationality"
              control={control}
              render={({ field }) => <Input {...field} placeholder="ไทย" />}
            />
          </Form.Item>
        </Col>
      </Row>

      <Row gutter={16}>
        <Col xs={24} md={12}>
          <Form.Item
            label="เลขบัตรประชาชน"
            required
            validateStatus={errors.nationalId ? 'error' : ''}
            help={errors.nationalId?.message}
          >
            <Controller
              name="nationalId"
              control={control}
              render={({ field }) => (
                <Input {...field} placeholder="1234567890123" maxLength={13} />
              )}
            />
          </Form.Item>
        </Col>
        <Col xs={24} md={12}>
          <Form.Item
            label="ศาสนา"
            validateStatus={errors.religion ? 'error' : ''}
            help={errors.religion?.message}
          >
            <Controller
              name="religion"
              control={control}
              render={({ field }) => <Input {...field} placeholder="พุทธ" />}
            />
          </Form.Item>
        </Col>
      </Row>

      {/* Emergency Contact */}
      <Title level={5} style={{ marginTop: '16px' }}>
        ผู้ติดต่อฉุกเฉิน
      </Title>
      <Row gutter={16}>
        <Col xs={24} md={8}>
          <Form.Item
            label="ชื่อผู้ติดต่อ"
            required
            validateStatus={errors.emergencyContactName ? 'error' : ''}
            help={errors.emergencyContactName?.message}
          >
            <Controller
              name="emergencyContactName"
              control={control}
              render={({ field }) => <Input {...field} placeholder="ชื่อผู้ติดต่อฉุกเฉิน" />}
            />
          </Form.Item>
        </Col>
        <Col xs={24} md={8}>
          <Form.Item
            label="ความสัมพันธ์"
            required
            validateStatus={errors.emergencyContactRelationship ? 'error' : ''}
            help={errors.emergencyContactRelationship?.message}
          >
            <Controller
              name="emergencyContactRelationship"
              control={control}
              render={({ field }) => (
                <Select {...field} placeholder="เลือกความสัมพันธ์">
                  <Select.Option value="พ่อ">พ่อ</Select.Option>
                  <Select.Option value="แม่">แม่</Select.Option>
                  <Select.Option value="คู่สมรส">คู่สมรส</Select.Option>
                  <Select.Option value="พี่น้อง">พี่น้อง</Select.Option>
                  <Select.Option value="อื่นๆ">อื่นๆ</Select.Option>
                </Select>
              )}
            />
          </Form.Item>
        </Col>
        <Col xs={24} md={8}>
          <Form.Item
            label="เบอร์โทรศัพท์"
            required
            validateStatus={errors.emergencyContactPhone ? 'error' : ''}
            help={errors.emergencyContactPhone?.message}
          >
            <Controller
              name="emergencyContactPhone"
              control={control}
              render={({ field }) => <Input {...field} placeholder="0812345678" maxLength={10} />}
            />
          </Form.Item>
        </Col>
      </Row>

      {/* Form Actions */}
      <Form.Item style={{ marginTop: '32px' }}>
        <Space>
          <Button onClick={onCancel}>ยกเลิก</Button>
          <Button type="primary" htmlType="submit">
            ถัดไป
          </Button>
        </Space>
      </Form.Item>
    </Form>
  );
};
